services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/
    environment:
      CHANNEL_ACCESS_TOKEN: ${CHANNEL_ACCESS_TOKEN}
      CHANNEL_SECRET: ${CHANNEL_SECRET}
    ports:
      - ${PORT}:8080
    restart: on-failure
